[workspace]
members = [".", "testing/e2e", "identity", "testing/itest"]

[workspace.package]
authors = ["Protocol Labs"]
edition = "2021"
license-file = "LICENSE"

[package]
name = "ipc-agent"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-channel = "1.8.0"
async-trait = "0.1.61"
futures = "0.3.28"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
indoc = "2.0.0"
log = { workspace = true }
reqwest = { version = "0.11.13", features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
cid = { version = "0.8.3", default-features = false, features = ["serde-codec"] }
tokio = { workspace = true }
tokio-stream = "0.1.12"
tokio-graceful-shutdown = "0.12.1"
tokio-tungstenite = { version = "0.18.0", features = ["native-tls"] }
derive_builder = "0.12.0"
num-traits = { workspace = true }
num-derive = "0.3.3"
env_logger = "0.10.0"
base64 = { workspace = true }
strum = { version = "0.24", features = ["derive"] }
toml = "0.7.2"
url = { version = "2.3.1", features = ["serde"] }
warp = "0.3.3"
bytes = "1.4.0"
serde_bytes = "0.11.9"
clap = { version = "4.1.4", features = ["env", "derive"] }
thiserror = { workspace = true }
hex = { workspace = true }
serde_tuple = "0.5.0"
zeroize = "1.6.0"

ethers-contract = { workspace = true }
ethers = { workspace = true }
fvm_shared = { workspace = true }
fil_actors_runtime = { workspace = true }
ipc-sdk = { workspace = true }
ipc-subnet-actor = { workspace = true }
ipc-gateway = { workspace = true }
fvm_ipld_encoding = { workspace = true }
primitives = { workspace = true }

ipc-identity = { path = "identity/.", features = ["with-ethers"] }

[dev-dependencies]
tempfile = { workspace = true }
hex = { workspace = true }

[workspace.dependencies]
anyhow = "1.0"
num-traits = "0.2.15"
base64 = "0.21.0"
lazy_static = "1.4"
log = "0.4"
env_logger = "0.10"
prometheus = "0.13"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.16", features = ["full"] }
thiserror = "1.0.38"
quickcheck = "1"
quickcheck_macros = "1"
blake2b_simd = "1.0"
rand = "0.8"
hex = "0.4.3"
tempfile = "3.4.0"
serde_json = { version = "1.0.91", features = ["raw_value"] }

fvm_ipld_blockstore = "0.1.1"
fvm_ipld_encoding = "0.3.3"
fvm_shared = { version = "=3.2.0", default-features = false, features = ["crypto"] }
fil_actors_runtime = { git = "https://github.com/consensus-shipyard/fvm-utils", features = ["fil-actor"] }
ipc-sdk = { git = "https://github.com/consensus-shipyard/ipc-actors.git" }
ipc-subnet-actor = { git = "https://github.com/consensus-shipyard/ipc-actors.git", features = [] }
ipc-gateway = { git = "https://github.com/consensus-shipyard/ipc-actors.git", features = [] }
libipld = { version = "0.14", default-features = false, features = ["dag-cbor"] }
primitives = { git = "https://github.com/consensus-shipyard/fvm-utils" }
ethers = { git = "https://github.com/cryptoAtwill/ethers-rs.git" }
ethers-contract = { git = "https://github.com/cryptoAtwill/ethers-rs.git" }

# Uncomment to point to you local versions
# [patch."https://github.com/consensus-shipyard/fvm-utils"]
# primitives = { path = "../fvm-utils/primitives" }
# fil_actors_runtime = { path = "../fvm-utils/runtime" }
