[workspace]
resolver = "2"
members = [
	# "ipc/daemon", 
	"ipc/cli",
	# "ipc/testing/e2e", 
	# "ipc/testing/*",
	"ipc/provider",
	"ipc/identity", 
	"ipc/sdk"
]

[workspace.package]
authors = ["Protocol Labs"]
edition = "2021"
license-file = "LICENSE"

[workspace.dependencies]
anyhow = "1.0"
reqwest = { version = "0.11.13", features = ["json"] }
async-trait = "0.1.73"
async-channel = "1.8.0"
url = { version = "2.3.1", features = ["serde"] }
num-traits = "0.2.15"
base64 = "0.21.0"
lazy_static = "1.4"
log = "0.4"
env_logger = "0.10"
cid = { version = "0.8.3", default-features = false, features = ["serde-codec"] }
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
prometheus = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_tuple = "0.5.0"
tokio = { version = "1.16", features = ["full"] }
tokio-tungstenite = { version = "0.18.0", features = ["native-tls"] }
thiserror = "1.0.38"
quickcheck = "1"
quickcheck_macros = "1"
blake2b_simd = "1.0"
rand = "0.8"
hex = "0.4.3"
tempfile = "3.4.0"
serde_json = { version = "1.0.91", features = ["raw_value"] }

ipc_actors_abis = { git = "https://github.com/consensus-shipyard/ipc-solidity-actors.git", branch = "dev" }

libipld = { version = "0.14", default-features = false, features = ["dag-cbor"] }
libsecp256k1 = "0.7"
ethers = "2.0.8"
ethers-contract = "2.0.8"

ipc-sdk = { path = "./ipc/sdk" }

fvm_ipld_blockstore = "0.1.1"
fvm_ipld_encoding = "0.3.3"
fvm_ipld_hamt = "0.6"
fvm_shared = { version = "=3.2.0", default-features = false, features = ["crypto"] }
fil_actors_runtime = { git = "https://github.com/consensus-shipyard/fvm-utils", features = ["fil-actor"] }
primitives = { git = "https://github.com/consensus-shipyard/fvm-utils" }

# Uncomment to point to you local versions
# [patch."https://github.com/consensus-shipyard/fvm-utils"]
# primitives = { path = "../fvm-utils/primitives" }
# fil_actors_runtime = { path = "../fvm-utils/runtime" }
