[server]
json_rpc_address = "127.0.0.1:3030"

[subnets]

[subnets.root]
id = "/root"
jsonrpc_api_http = "https://example.org/rpc/v0"
jsonrpc_api_ws = "wss://example.org/rpc/v0"
auth_token = "YOUR ROOT AUTH TOKEN"

[subnets.child]
id = "/root/t0100"
jsonrpc_api_http = "https://example.org/rpc/v2"
auth_token = "YOUR CHILD AUTH TOKEN"
accounts = ["t3thgjtvoi65yzdcoifgqh6utjbaod3ukidxrx34heu34d6avx6z7r5766t5jqt42a44ehzcnw3u5ehz47n42a"]